// Build step for the public team website.
//
// Two jobs:
//   1. Copy the design system out of "06 Design System/" into site/_ds/feb/,
//      so the site links the repo's own copy instead of carrying a third one.
//      The generated directory is gitignored. Never edit it.
//   2. Check that the shared nav and footer blocks are identical across every
//      page. The pages are hand-written with no templating, which keeps them
//      openable and editable, but it means the nav can drift. This catches it.
//
//   node "08 Website/build.mjs"          build, then check
//   node "08 Website/build.mjs" --check  check only, no writes (used by tests)

import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const DS_SRC = join(ROOT, '06 Design System');
const SITE = join(HERE, 'site');
const DS_OUT = join(SITE, '_ds', 'feb');
const CHECK_ONLY = process.argv.includes('--check');

let failures = 0;
const fail = (msg) => { console.error(`✗ ${msg}`); failures++; };

// ── 1. design system ────────────────────────────────────────────────────────
// tokens.css declares @font-face with url('fonts/…'), so fonts/ has to land
// beside it for the reference to resolve. Same layout as the design handoff's
// bundled _ds/feb/, which is byte-identical to what this produces.
if (!CHECK_ONLY) {
  for (const f of ['tokens.css', 'components.css']) {
    if (!existsSync(join(DS_SRC, f))) { fail(`missing ${f} in "06 Design System/"`); }
  }
  if (failures) process.exit(1);

  rmSync(DS_OUT, { recursive: true, force: true });
  mkdirSync(DS_OUT, { recursive: true });
  cpSync(join(DS_SRC, 'tokens.css'), join(DS_OUT, 'tokens.css'));
  cpSync(join(DS_SRC, 'components.css'), join(DS_OUT, 'components.css'));
  cpSync(join(DS_SRC, 'fonts'), join(DS_OUT, 'fonts'), { recursive: true });
  writeFileSync(
    join(DS_OUT, 'styles.css'),
    '/* Generated by "08 Website/build.mjs" from "06 Design System/". Do not edit. */\n' +
      '@import "./tokens.css";\n@import "./components.css";\n',
  );
  console.log(`✓ design system → site/_ds/feb/ (from "06 Design System/")`);
}

// ── 2. shared-block drift check ─────────────────────────────────────────────
// Each page wraps its nav and footer in <!-- shared:nav --> … <!-- /shared:nav -->
// markers. Every page's block must match the one in index.html, ignoring the
// per-page active-link markers (aria-current and the "active" class).
const pages = readdirSync(SITE).filter((f) => f.endsWith('.html')).sort();
if (!pages.length) fail('no pages found in site/');

const block = (html, name) => {
  const m = html.match(new RegExp(`<!-- shared:${name} -->([\\s\\S]*?)<!-- /shared:${name} -->`));
  return m ? m[1] : null;
};
// Active state is legitimately per-page; normalize it away before comparing.
const normalize = (s) => s.replace(/ class="active"/g, '').replace(/ aria-current="page"/g, '').trim();

for (const name of ['nav', 'footer']) {
  const ref = block(readFileSync(join(SITE, 'index.html'), 'utf8'), name);
  if (!ref) { fail(`index.html has no shared:${name} block`); continue; }
  for (const p of pages) {
    if (p === 'index.html') continue;
    const got = block(readFileSync(join(SITE, p), 'utf8'), name);
    if (got === null) fail(`${p} has no shared:${name} block`);
    else if (normalize(got) !== normalize(ref)) fail(`${p}: shared:${name} drifted from index.html`);
  }
}

if (failures) {
  console.error(`\n${failures} problem(s). The shared blocks are copied by hand; re-sync them from index.html.`);
  process.exit(1);
}
console.log(`✓ ${pages.length} pages, nav and footer in sync`);
